EasyBusProject/Models/Ticket.cs
using EasyBus.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EasyBusProject.Models
{
    public class Ticket
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("User")]
        public int UserId { get; set; }
        public User? User { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateOnly Date { get; set; }

        [Required]
        [DataType(DataType.Time)]
        public TimeOnly Time { get; set; }

        [Required(ErrorMessage = "Number of seats is not Valid !")]
        public int NumOfAvailSeats { get; set; }

        [Required(ErrorMessage = "Bus name is required.")]
        public string BusName { get; set; }

        public int Price { get; set; }

        [Required(ErrorMessage = "Start location is required.")]
        public string StartFrom { get; set; }

        [Required(ErrorMessage = "Destination is required.")]
        public string Destination { get; set; }

        
        //[Range(1,52,ErrorMessage ="Please choose seats")]
        public int NumOfSeatsOfUser { get; set; }

        public int TotalCapacity { get; set; }

        public string? Seats { get; set; }
    }
}

EasyBusProject/ViewModels/TicketViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EasyBusProject.ViewModels
{
    public class TicketViewModel
    {
        [Key]
        public int Id { get; set; }
        public string UserName { get; set; }

        [DataType(DataType.Date)]
        public DateOnly Date { get; set; }
        
        [DataType(DataType.Time)]
        public TimeOnly Time { get; set; }

        public string BusName { get; set; }
        public int Price { get; set; }
        public string StartFrom { get; set; }
        public string Destination { get; set; }
        public int NumOfSeatsOfUser { get; set; }
    }
}

EasyBusProject/Controllers/SeatsController.cs
using EasyBusProject.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;
using System.Text.Json;

namespace EasyBusProject.Controllers
{
    public class SeatsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public class MyModel
        {
            public Dictionary<string,bool> Data { get; set; }
        }

        [HttpPost]
        public IActionResult Index(CheckBoxViewModel checkBoxViewModel)
        {
            TempData["name"] = "Moe";
            TempData["noOfSeats"] = checkBoxViewModel.CheckboxValues.Count;

            ViewData["seats"] = checkBoxViewModel;
            string json = JsonSerializer.Serialize(checkBoxViewModel);
            TempData["SerializedDictionary"] = json;
            return RedirectToAction("TicketsView");
        }

        public IActionResult TicketsView()
        {
            string name = TempData["name"] as string;
            string json = TempData["SerializedDictionary"] as string;

            CheckBoxViewModel seats = JsonSerializer.Deserialize<CheckBoxViewModel>(json);

            var noOfSeats = TempData["noOfSeats"];

            ViewBag.DataReceived = name;
            ViewBag.NumberOfSeats = noOfSeats;
            ViewBag.Seats = seats.CheckboxValues;
            return View();
        }

    }
}

EasyBusProject/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyBus.Models;
using EasyBusProject.Models;
using System.Security.Claims;

namespace EasyBusProject.Controllers
{
    public class TicketsController : Controller
    {
        private readonly MainDbContext _context;

        public TicketsController(MainDbContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public IActionResult Index()
        {
            var currentUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var currentDate = DateOnly.FromDateTime(DateTime.Now);
            var mainDbContext = _context.Tickets
                                .Include(t => t.User)
                                .Where(u => u.UserId == currentUserId && u.Date >= currentDate)
                                .ToList();
            return View(mainDbContext);
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,Date,Time,NumOfAvailSeats,BusName,Price,StartFrom,Destination,NumOfSeatsOfUser,TotalCapacity,Seats")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", ticket.UserId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", ticket.UserId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Date,Time,NumOfAvailSeats,BusName,Price,StartFrom,Destination,NumOfSeatsOfUser,TotalCapacity,Seats")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", ticket.UserId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket != null)
            {
                _context.Tickets.Remove(ticket);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

EasyBusProject/Views/Seats/Index.cshtml
@model EasyBusProject.ViewModels.CheckBoxViewModel
@{
    ViewData["Title"] = "Index";
}

<style>
    input {
        
    }
    .bus {
        background-color: #FEC91B;
        width: 250px;
        padding-bottom: 20px;
        border-top-left-radius: 20px;
        border-top-right-radius: 20px;

        border-bottom-left-radius: 20px;
        border-bottom-right-radius: 20px;

        border-width: 4px;
        border-color:black;
        border-style: solid;
    }
    img {
        margin-top:25px;
        margin-left:17px;
    }

    .custom-checkbox {
        width:40px;
        height: 40px;
        border-radius: 5px;
        background-color:white;

        cursor:pointer;

        margin-top: 5px;
    }

    input[type="checkbox"]:checked + .custom-checkbox {
        /* Your styles for the label when the checkbox is checked */
        /* For example, change color */
        background-color: lightgreen;
    }

    label {
        width:20px;
        height:20px;
    }

</style>

<h1>Index</h1>


    @using (Html.BeginForm("Index", "Seats", FormMethod.Post))
    {
    <div class="container bus">
        @{
            var i = 1; int[] nums = [1, 2, 3, 4, 5, 6, 7,8,9,10];
        }
        <img width="40px" src="~/Images/steering-wheel-transparent-background-15.png"/>
        <hr />
        @foreach (var item in nums)
        {
            <div class="row">
                <div class="col text-center">

                    <input hidden data-val="true" data-val-required="The Boolean field is required." id="S @i" name="CheckboxValues[@i]" type="checkbox" value="true" />
                    <label for="S @i" class="custom-checkbox"><b>@i</b></label>
                    @{
                        i++;
                    }


                    <input hidden data-val="true" data-val-required="The Boolean field is required." id="S @i" name="CheckboxValues[@i]" type="checkbox" value="true" />
                    <label for="S @i" class="custom-checkbox"><b>@i</b></label>
                    @{
                        i++;
                    }


                    <input hidden style="margin-left:20px;" data-val="true" data-val-required="The Boolean field is required." id="S @i" name="CheckboxValues[@i]" type="checkbox" value="true" />
                    <label for="S @i" style="margin-left:20px;" class="custom-checkbox"><b>@i</b></label>
                    @{
                        i++;
                    }


                    <input hidden data-val="true" data-val-required="The Boolean field is required." id="S @i" name="CheckboxValues[@i]" type="checkbox" value="true" />
                    <label for="S @i" class="custom-checkbox"><b>@i</b></label>
                    @{
                        i++;
                    }

                </div>
            </div>

        }
            
        </div>

        <div class="text-center mt-5 mb-3">
            <input class="btn btn-warning" type="submit" value="Buy Seats" />
        </div>
    }

EasyBusProject/Views/Seats/TicketsView.cshtml
@model EasyBusProject.ViewModels.CheckBoxViewModel

@{
    ViewData["Title"] = "TicketsView";
}

<style>
    .card {
        margin: 20px;
    }
</style>

<div class="container">
    <div class="row">
        @foreach (var item in ViewBag.Seats)
        {
            <div class="col-12 col-md-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Ticket</h5>
                        <p class="card-text"></p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">An item</li>
                        <li class="list-group-item">A second item</li>
                        <li class="list-group-item">A third item</li>
                    </ul>
                </div>
            </div>
        }


    </div>
</div>